# Generated by Django 4.1.3 on 2022-12-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=30)),
                ('pass_fail', models.CharField(max_length=5)),
            ],
        ),
    ]
